In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("tam_eslesme_sonuclari.tsv", sep="\t")

In [3]:
df.columns

Index(['Ingredient', 'IDs', '__index_level_0__', 'I-NAME tokens',
       'Matched Words', 'En Uzun Tam Eşleşme'],
      dtype='object')

In [4]:
df.head()

,Ingredient,IDs,__index_level_0__,I-NAME tokens,Matched Words,En Uzun Tam Eşleşme
0,low sodium vegetable,"0, 11434, 14768, 96363, 105999, 194867, 255566...",0,"▁vegeta, ble",vegetable,vegetable
1,chicken stock,"0, 11, 94, 101, 130, 155, 345, 678, 852, 876, ...",1,"▁chicken, ▁stock","chicken, stock",chicken stock
2,dried brown lentils,"0, 17104, 836751, 838386, 841486, 871267, 8744...",2,"▁brown, ▁lenti, ls","brown, lentils",brown lentils
3,dried French green lentils,"0, 2684, 3173, 3530, 16691",3,"▁French, ▁green, ▁lenti, ls","French, green, lentils",french green lentils
4,"celery, chopped","0, 1149, 2427, 3530, 5081, 5340, 5891, 8907, 9...",4,"▁cele, ry","celery,",celery

In [5]:
df.tail()

,Ingredient,IDs,__index_level_0__,I-NAME tokens,Matched Words,En Uzun Tam Eşleşme
505057,s Sweet Mustard Sauce for Pretzels and More,1171959,505058,"▁Sweet, ▁Musta, rd, ▁Sau, ce","Sweet, Mustard, Sauce",sweet mustard sauce
505058,Orange Ginger Broiled Pork Tenderloin,1172243,505059,"▁Orange, ▁G, inger, ▁Por, k, ▁Ten, der, lo, in","Orange, Ginger, Pork, Tenderloin",orange ginger broiled pork tenderloin
505059,Garlic Herb Infused Skewers,1173044,505060,"▁Gar, lic, ▁Her, b","Garlic, Herb",garlic herb
505060,dehydrated celery,1173557,505061,"▁cele, ry",celery,celery
505061,alfredo noodles,1173818,505062,"▁al, fred, o, ▁nood, les","alfredo, noodles",alfredo noodles

In [6]:
def get_unique_id_set(df, match_column="En Uzun Tam Eşleşme", id_column="IDs"):
    df["word_count"] = df[match_column].fillna("").apply(lambda x: len(x.split()))

    filtered_df = df[df["word_count"] > 4]

    unique_id_set = set(filtered_df[id_column].unique())

    return unique_id_set

In [7]:
unique_id_set = get_unique_id_set(df)

In [8]:
len(unique_id_set)

31709

In [9]:
df = pd.read_parquet("merged_and_cleaned_all_data.parquet", engine="pyarrow")

In [10]:
unique_id_list = []
for item in unique_id_set:
    parts = item.split(",")  
    for p in parts:
        p = p.strip()  
        unique_id_list.append(int(p))

In [11]:
unique_id_list

[399371,
 557,
 4221,
 517186,
 598050,
 110500,
 137655,
 11294,
 261050,
 555184,
 511791,
 230988,
 115923,
 283003,
 409303,
 412553,
 481916,
 496280,
 541642,
 717289,
 754466,
 760014,
 763171,
 130541,
 452289,
 744122,
 81062,
 702151,
 187112,
 478170,
 521678,
 136534,
 769495,
 560319,
 11912,
 62655,
 123727,
 129768,
 483539,
 578067,
 605629,
 714194,
 794632,
 473752,
 117919,
 131968,
 608347,
 751104,
 209488,
 779367,
 588047,
 600163,
 412010,
 583137,
 108776,
 735889,
 206558,
 740380,
 2700,
 174573,
 189780,
 547772,
 531102,
 110129,
 215821,
 368332,
 694009,
 663602,
 177934,
 793818,
 429959,
 581694,
 687156,
 343299,
 304393,
 269033,
 628429,
 810240,
 267089,
 688213,
 200551,
 194962,
 660496,
 669031,
 104879,
 88417,
 767846,
 498106,
 507024,
 779009,
 460369,
 598955,
 493953,
 509773,
 172679,
 726161,
 465227,
 103221,
 382577,
 246480,
 623550,
 184519,
 275839,
 576298,
 73095,
 223714,
 501712,
 4291,
 402313,
 776937,
 281530,
 505610,
 619882,
 144791,
 674755,
 270862,
 289117,
 351737,
 698679,
 361117,
 372268,
 399434,
 333017,
 23,
 529338,
 350814,
 263168,
 271111,
 638213,
 644924,
 820407,
 8491,
 13214,
 91238,
 771748,
 147592,
 15334,
 239009,
 614962,
 577431,
 400718,
 103800,
 332463,
 680710,
 93405,
 276400,
 797511,
 434444,
 675302,
 5328,
 335752,
 956560,
 101978,
 113833,
 140563,
 168550,
 204922,
 512342,
 640016,
 665715,
 691082,
 694046,
 776527,
 732736,
 97981,
 764695,
 583342,
 170109,
 152186,
 532733,
 615006,
 617361,
 795240,
 235941,
 496474,
 66445,
 370539,
 393745,
 466624,
 780637,
 98719,
 12983,
 642649,
 655673,
 666239,
 474999,
 241741,
 466120,
 665426,
 407227,
 376137,
 212334,
 283704,
 241881,
 235873,
 468844,
 104770,
 117330,
 223802,
 689938,
 173749,
 742428,
 351582,
 229516,
 330531,
 292929,
 577239,
 818899,
 616537,
 674711,
 281955,
 244695,
 626982,
 815229,
 94502,
 517578,
 810837,
 90833,
 729610,
 139400,
 508916,
 202251,
 598285,
 764540,
 108740,
 138168,
 382135,
 532371,
 388172,
 2340,
 262289,
 539135,
 688163,
 584299,
 662429,
 144144,
 79448,
 452520,
 292563,
 746222,
 772198,
 773420,
 135271,
 478906,
 366405,
 116350,
 199977,
 464435,
 161466,
 681601,
 243519,
 593908,
 515283,
 628616,
 100926,
 133400,
 324692,
 419496,
 554468,
 651895,
 763120,
 103764,
 114826,
 490660,
 178968,
 154565,
 307461,
 646351,
 2552,
 700612,
 308417,
 144780,
 183917,
 283621,
 295838,
 333204,
 392285,
 413356,
 456123,
 481564,
 656154,
 753479,
 812691,
 145263,
 390312,
 481919,
 584962,
 649533,
 90960,
 634032,
 482511,
 497692,
 6715,
 11917,
 233915,
 258045,
 443327,
 465079,
 71343,
 559558,
 688736,
 673966,
 463252,
 192440,
 230522,
 246274,
 247630,
 263216,
 304315,
 530598,
 571155,
 604180,
 635135,
 662461,
 672134,
 748910,
 776408,
 114732,
 484975,
 66457,
 393374,
 566770,
 395299,
 61414,
 197979,
 536041,
 282671,
 702221,
 561634,
 602108,
 558457,
 237819,
 210411,
 365761,
 465664,
 757750,
 643085,
 549581,
 1086041,
 135778,
 585042,
 779166,
 802998,
 773475,
 615167,
 655713,
 386627,
 607478,
 189151,
 401611,
 14022,
 77401,
 186575,
 208493,
 215726,
 279436,
 290724,
 395262,
 607903,
 607947,
 609914,
 716436,
 747568,
 756865,
 363762,
 721382,
 795317,
 657403,
 723401,
 744801,
 634840,
 997949,
 664733,
 794931,
 150773,
 771124,
 364378,
 97011,
 102697,
 322430,
 353008,
 436555,
 580775,
 812871,
 274985,
 192582,
 292386,
 350001,
 684818,
 687238,
 539968,
 298056,
 648010,
 536814,
 66050,
 79014,
 170363,
 203469,
 243636,
 246690,
 270943,
 288394,
 319310,
 321014,
 333160,
 399641,
 436819,
 464319,
 484515,
 617958,
 621481,
 724655,
 729288,
 731241,
 768642,
 770281,
 798886,
 810111,
 395055,
 207545,
 714868,
 272920,
 416122,
 453168,
 209270,
 237364,
 602231,
 198791,
 443303,
 548511,
 202933,
 423386,
 218487,
 123910,
 78142,
 90522,
 117426,
 128126,
 156133,
 191643,
 292391,
 308555,
 324737,
 362519,
 388681,
 412146,
 427574,
 441473,
 447195,
 540466,
 574312,
 602497,
 607366,
 630504,
 720825,
 734339,
 739094,
 780453,
 807103,
 812216,
 823047,
 858567,
 898093,
 898094,
 898095,
 929519,
 988946,
 991617,
 999915,
 1013266,
 1030597,
 1048308,
 1048309,
 1048310,
 1048311,
 1050168,
 1059589,
 1065683,
 1071960,
 1073375,
 1079429,
 1088347,
 1088742,
 1103991,
 1106046,
 1125659,
 1143786,
 1145708,
 254529,
 110191,
 615423,
 368413,
 320346,
 9792,
 89926,
 193606,
 316989,
 395276,
 360862,
 308872,
 168704,
 288858,
 745045,
 777701,
 246494,
 61578,
 77007,
 78880,
 101180,
 103984,
 104843,
 108150,
 177709,
 192035,
 200687,
 215101,
 217503,
 221436,
 227816,
 258092,
 263989,
 269121,
 307884,
 308715,
 310629,
 313089,
 330524,
 338931,
 339795,
 342346,
 346605,
 366947,
 406789,
 406914,
 410865,
 422597,
 444515,
 449787,
 475336,
 481040,
 481794,
 501929,
 519260,
 520625,
 548800,
 564455,
 567703,
 569912,
 570154,
 573498,
 601876,
 605059,
 618995,
 648038,
 666822,
 670199,
 696614,
 701378,
 701831,
 708831,
 709977,
 720857,
 727014,
 743198,
 784384,
 797532,
 799969,
 815920,
 147828,
 673459,
 691640,
 807672,
 112151,
 470688,
 710160,
 562476,
 64767,
 509307,
 786925,
 698180,
 6080,
 7381,
 15697,
 536538,
 299826,
 464138,
 637321,
 777730,
 622475,
 62814,
 1299,
 11662,
 147104,
 449272,
 608909,
 396632,
 624503,
 221838,
 493905,
 419056,
 102980,
 244288,
 705350,
 621695,
 644986,
 792226,
 817535,
 692316,
 3057,
 567348,
 195670,
 5424,
 221252,
 100457,
 431180,
 203719,
 224486,
 244157,
 299127,
 387453,
 438886,
 455387,
 542563,
 132980,
 75308,
 173275,
 215087,
 298839,
 445975,
 473802,
 493735,
 636711,
 687695,
 814405,
 632781,
 9858,
 388210,
 405470,
 77242,
 397651,
 84984,
 819381,
 653948,
 760066,
 97552,
 319533,
 646079,
 368260,
 564514,
 774447,
 90973,
 470988,
 338939,
 176805,
 807190,
 77856,
 236822,
 240146,
 279258,
 283944,
 375102,
 405137,
 443072,
 502144,
 517830,
 646262,
 657138,
 754277,
 803582,
 147839,
 4947,
 239888,
 97588,
 262653,
 322665,
 1042,
 10580,
 93194,
 671364,
 235,
 788489,
 177491,
 351745,
 379698,
 424988,
 807067,
 253935,
 12324,
 64613,
 95113,
 132536,
 140128,
 747467,
 488929,
 595229,
 66262,
 78043,
 238677,
 415653,
 802062,
 961,
 4680,
 81588,
 486736,
 397346,
 797449,
 581384,
 720814,
 468500,
 4218,
 791362,
 729395,
 670411,
 382376,
 199348,
 212068,
 337164,
 398538,
 421781,
 654474,
 665922,
 761615,
 329736,
 414139,
 715275,
 260709,
 603749,
 394489,
 187192,
 64026,
 527358,
 152385,
 613186,
 788454,
 471336,
 444361,
 598465,
 806736,
 415744,
 261418,
 469615,
 489745,
 440558,
 162392,
 722585,
 467721,
 442568,
 573301,
 251220,
 339181,
 141940,
 332740,
 426775,
 328886,
 64279,
 70639,
 125264,
 184881,
 209313,
 284252,
 326421,
 374435,
 400350,
 477014,
 618147,
 639072,
 648670,
 667476,
 761441,
 777449,
 810639,
 355651,
 554841,
 598284,
 619261,
 375437,
 430560,
 319385,
 371035,
 109989,
 199938,
 231894,
 337410,
 548554,
 638479,
 725957,
 803692,
 63988,
 151126,
 458998,
 422627,
 82824,
 666233,
 594922,
 551073,
 181450,
 795726,
 163951,
 930190,
 507896,
 365723,
 407567,
 769802,
 698165,
 816138,
 14821,
 230654,
 12579,
 99548,
 553487,
 232495,
 425807,
 409228,
 82496,
 248829,
 700102,
 738285,
 236695,
 300852,
 591204,
 305524,
 353376,
 752466,
 285797,
 3508,
 474318,
 415705,
 1805,
 7877,
 593057,
 545549,
 772262,
 623669,
 243302,
 604276,
 450284,
 647746,
 745700,
 202798,
 307491,
 321917,
 675917,
 631625,
 13998,
 221044,
 593128,
 423790,
 678249,
 160856,
 335492,
 739949,
 11850,
 319924,
 597874,
 633576,
 439551,
 103559,
 611358,
 734817,
 719583,
 355409,
 306434,
 651086,
 100687,
 79296,
 471058,
 648458,
 756488,
 761971,
 493138,
 161222,
 569704,
 128784,
 163746,
 645169,
 751473,
 463830,
 154004,
 193606,
 660714,
 1760,
 356189,
 657516,
 11718,
 531994,
 400968,
 749749,
 734579,
 234427,
 603368,
 279260,
 288493,
 696721,
 607976,
 396956,
 457764,
 780187,
 9628,
 666272,
 503922,
 113581,
 662121,
 297307,
 304354,
 691133,
 565700,
 764049,
 328949,
 431081,
 1048636,
 173850,
 226261,
 820531,
 404872,
 8976,
 499323,
 76070,
 79989,
 107316,
 155619,
 203326,
 408897,
 410672,
 635149,
 798049,
 94456,
 248138,
 304111,
 383722,
 404657,
 619516,
 635805,
 214035,
 289412,
 329299,
 683513,
 424177,
 766716,
 631326,
 460578,
 457848,
 652992,
 232205,
 11239,
 132286,
 464464,
 494931,
 327651,
 516184,
 649948,
 357207,
 148765,
 221125,
 316204,
 12946,
 741315,
 622962,
 250702,
 423440,
 216889,
 679855,
 521711,
 285926,
 356251,
 576782,
 809340,
 238269,
 171270,
 168355,
 615417,
 447892,
 633345,
 579900,
 221216,
 241161,
 667135,
 68439,
 392823,
 647737,
 84573,
 102844,
 645308,
 677068,
 358001,
 386613,
 323914,
 493597,
 133084,
 268812,
 344453,
 665212,
 467866,
 76594,
 539187,
 703060,
 813691,
 271112,
 410019,
 651724,
 661298,
 ...]

In [12]:
filtered_df = df[df["ID"].isin(unique_id_list)]
print(len(filtered_df))
filtered_df.to_parquet("problematic_recipes.parquet", engine="pyarrow")

74975

In [13]:
remaining_df = df[~df["ID"].isin(unique_id_list)]
remaining_df.to_parquet("non-problematic_recipes.parquet", engine="pyarrow")