In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("tam_eslesme_sonuclari.tsv", sep="\t")

In [3]:
df.columns

Index(['Ingredient', 'IDs', '__index_level_0__', 'I-NAME tokens',
       'Matched Words', 'En Uzun Tam Eşleşme'],
      dtype='object')

In [4]:
df.head()

,Ingredient,IDs,__index_level_0__,I-NAME tokens,Matched Words,En Uzun Tam Eşleşme
0,low-sodium vegetable,"0, 11434, 14768, 82089, 96363, 105999, 194867,...",0,"▁vegeta, ble",vegetable,vegetable
1,chicken stock,"0, 11, 94, 101, 130, 155, 200, 345, 552, 678, ...",1,"▁chicken, ▁stock","chicken, stock",chicken stock
2,dried brown lentils,"0, 17104, 836751, 838386, 841486, 871267, 8744...",2,"▁brown, ▁lenti, ls","brown, lentils",brown lentils
3,dried french green lentils,"0, 2684, 3173, 3530, 16691",3,"▁fren, ch, ▁green, ▁lenti, ls","french, green, lentils",french green lentils
4,"celery, chopped","0, 1149, 2427, 3530, 5081, 5340, 5891, 8907, 9...",4,"▁cele, ry",celery,celery

In [5]:
df.tail()

,Ingredient,IDs,__index_level_0__,I-NAME tokens,Matched Words,En Uzun Tam Eşleşme
549649,s sweet mustard sauce for pretzels and more,1171959,549651,"▁sweet, ▁must, ard, ▁sauce","sweet, mustard, sauce",sweet mustard sauce
549650,orange-ginger broiled pork tenderloin,1172243,549652,"▁orang, e, ging, er, led, ▁por, k, ▁tender, lo...","orange-ginger, broiled, pork, tenderloin",orange-ginger broiled pork tenderloin
549651,garlic herb infused skewers,1173044,549653,"▁gar, lic, ▁her, b","garlic, herb",garlic herb
549652,alfredo noodles mix,1173818,549654,"▁al, fred, o, ▁nood, les, ▁mix","alfredo, noodles, mix",alfredo noodles mix
549653,instant devil's food pudding mix,1173972,549655,"▁instant, ▁de, vil, ', s, ▁food, ▁pu, dding, ▁mix","instant, devil's, food, pudding, mix",instant devil's food pudding mix

In [6]:
def get_unique_id_set(df, match_column="En Uzun Tam Eşleşme", id_column="IDs"):
    df["word_count"] = df[match_column].fillna("").apply(lambda x: len(x.split()))

    filtered_df = df[df["word_count"] > 4]

    unique_id_set = set(filtered_df[id_column].unique())

    return unique_id_set

In [7]:
unique_id_set = get_unique_id_set(df)

In [8]:
len(unique_id_set)

36692

In [9]:
df = pd.read_parquet("merged_and_cleaned_all_data.parquet", engine="pyarrow")

In [10]:
# The recipes with 130350, 151885, 275952, 326407, 381514, 428479, 445989, 450835, 646986, 653053, 717383, 749572, 808681 IDs must be deleted.
ids_to_remove = [130350, 151885, 275952, 326407,381514, 428479, 445989, 450835, 646986, 653053, 717383, 749572, 808681]
index_names = df[df['ID'].isin(ids_to_remove)].index
df.drop(index_names, inplace=True)

In [11]:
unique_id_list = []
for item in unique_id_set:
    parts = item.split(",")  
    for p in parts:
        p = p.strip()  
        unique_id_list.append(int(p))

In [12]:
unique_id_list

[173314,
 274224,
 14148,
 676298,
 644572,
 144532,
 671362,
 784523,
 470982,
 5762,
 647238,
 275688,
 242065,
 142733,
 727817,
 803655,
 523367,
 344580,
 476280,
 619455,
 184515,
 475,
 171813,
 412551,
 634980,
 819151,
 781205,
 748187,
 465718,
 254916,
 700328,
 336275,
 613081,
 673443,
 196335,
 219644,
 439691,
 775723,
 544905,
 62215,
 268305,
 515267,
 172453,
 154347,
 791488,
 70173,
 416257,
 456200,
 796794,
 158532,
 346533,
 376861,
 136077,
 530278,
 613067,
 1394,
 586487,
 173368,
 175120,
 108070,
 524859,
 664235,
 73097,
 645798,
 626428,
 241984,
 286394,
 480578,
 791392,
 649722,
 82180,
 101259,
 163961,
 173812,
 199052,
 239206,
 338907,
 392018,
 402837,
 423442,
 444951,
 615418,
 633306,
 639278,
 665539,
 701821,
 732250,
 738399,
 748469,
 808702,
 594587,
 367364,
 395420,
 518756,
 708687,
 713805,
 802410,
 85306,
 912158,
 436529,
 98926,
 348111,
 732392,
 113024,
 340034,
 564336,
 600917,
 792294,
 128473,
 511535,
 385429,
 370999,
 139202,
 714395,
 17027,
 292343,
 330009,
 341947,
 226888,
 433627,
 731212,
 154827,
 159847,
 293633,
 403310,
 452570,
 514822,
 523196,
 523553,
 555425,
 745137,
 773284,
 793930,
 804135,
 450934,
 472773,
 586137,
 99321,
 225714,
 288108,
 740303,
 236310,
 239585,
 345208,
 186918,
 312975,
 435600,
 195872,
 617516,
 729736,
 1315,
 285222,
 225831,
 707054,
 7639,
 426566,
 755491,
 78926,
 569967,
 405064,
 407415,
 274183,
 516336,
 247336,
 740104,
 802150,
 92822,
 225505,
 380693,
 436063,
 511929,
 614883,
 186696,
 5214,
 531741,
 601575,
 84214,
 98078,
 502769,
 563925,
 639160,
 672239,
 119828,
 705454,
 537814,
 652471,
 124319,
 138412,
 356068,
 401988,
 17599,
 723388,
 147990,
 725774,
 382352,
 632845,
 302993,
 7704,
 575702,
 745131,
 12995,
 85066,
 788231,
 101514,
 623328,
 649931,
 796321,
 2824,
 84972,
 404169,
 603287,
 780187,
 596283,
 622366,
 619611,
 323989,
 541813,
 591084,
 714327,
 251742,
 230146,
 674816,
 2760,
 151626,
 353247,
 819634,
 631660,
 518238,
 594799,
 440844,
 793760,
 115732,
 494478,
 139867,
 161268,
 192078,
 675441,
 739254,
 471585,
 3638,
 675241,
 517220,
 358556,
 179100,
 330499,
 116597,
 130656,
 140447,
 189787,
 192317,
 207729,
 309279,
 329067,
 332180,
 367925,
 368619,
 401429,
 413251,
 450025,
 470978,
 490762,
 500524,
 539820,
 540763,
 553217,
 557155,
 575199,
 576467,
 594496,
 630459,
 631283,
 634113,
 649347,
 664386,
 679179,
 708935,
 750353,
 123231,
 180854,
 182494,
 313955,
 412574,
 462316,
 660295,
 276199,
 339967,
 668066,
 138812,
 749937,
 72571,
 115754,
 209158,
 323102,
 466488,
 625329,
 724199,
 784475,
 403646,
 450063,
 405358,
 290747,
 129981,
 389897,
 470825,
 502359,
 725153,
 458844,
 311174,
 111793,
 515831,
 396677,
 737943,
 783882,
 84851,
 574535,
 564151,
 380768,
 531314,
 171378,
 707451,
 748254,
 468585,
 218346,
 401341,
 568519,
 634854,
 377589,
 236916,
 537341,
 574823,
 243724,
 265318,
 387325,
 441940,
 516703,
 580176,
 306429,
 694222,
 112973,
 167081,
 472692,
 13883,
 77718,
 272830,
 133897,
 557145,
 702898,
 785569,
 316580,
 656166,
 406777,
 441787,
 596714,
 701913,
 536212,
 81850,
 103920,
 109446,
 118791,
 121371,
 130474,
 138970,
 150092,
 157277,
 161484,
 180084,
 187658,
 187754,
 202635,
 216119,
 225665,
 227584,
 236731,
 266873,
 272031,
 279562,
 288881,
 296005,
 297938,
 307509,
 335311,
 352521,
 366980,
 372072,
 377969,
 390625,
 407398,
 423055,
 442919,
 453709,
 463023,
 485118,
 498363,
 501795,
 501937,
 506707,
 520601,
 522895,
 525052,
 525126,
 527999,
 537207,
 539763,
 576231,
 587600,
 596499,
 597501,
 599877,
 602819,
 622240,
 651749,
 652323,
 665106,
 672986,
 674084,
 674668,
 683120,
 683286,
 707064,
 723211,
 730734,
 733012,
 735723,
 756643,
 759592,
 760732,
 761529,
 815016,
 817960,
 785076,
 753986,
 470495,
 151570,
 158967,
 278987,
 291793,
 348221,
 353258,
 461404,
 584592,
 591070,
 622331,
 703734,
 790836,
 557676,
 765285,
 554750,
 726481,
 138634,
 720317,
 474073,
 337926,
 172234,
 507298,
 518996,
 183071,
 148786,
 296457,
 254680,
 504054,
 614084,
 370619,
 437470,
 597416,
 688587,
 812247,
 132052,
 521713,
 288249,
 498041,
 762247,
 140502,
 283501,
 370901,
 756766,
 257146,
 413989,
 375970,
 253500,
 248836,
 86130,
 334632,
 519444,
 537201,
 557409,
 115831,
 413611,
 733476,
 760747,
 654180,
 314812,
 784755,
 222848,
 248267,
 490674,
 524177,
 752251,
 798893,
 499323,
 690019,
 331440,
 349621,
 83530,
 428721,
 442963,
 501342,
 538693,
 567444,
 97096,
 466552,
 803226,
 135225,
 229024,
 322236,
 350593,
 566520,
 297410,
 409309,
 812152,
 356220,
 734525,
 356528,
 444212,
 168704,
 288858,
 745045,
 777701,
 581648,
 688100,
 605827,
 213688,
 9077,
 754874,
 288303,
 377299,
 384850,
 177254,
 91768,
 113556,
 119253,
 131060,
 150686,
 159463,
 198499,
 204312,
 210492,
 218335,
 262820,
 269756,
 378417,
 390079,
 409349,
 464347,
 480684,
 482542,
 494589,
 495718,
 510562,
 518933,
 529569,
 532776,
 548749,
 570028,
 628806,
 631395,
 639565,
 651370,
 667808,
 679044,
 685875,
 687869,
 692118,
 706968,
 707719,
 736840,
 743882,
 747292,
 749358,
 756210,
 800607,
 811283,
 813213,
 783688,
 213020,
 250479,
 812823,
 703249,
 720559,
 756670,
 210381,
 4023,
 814765,
 758435,
 10845,
 689364,
 143247,
 669346,
 645848,
 311451,
 1526,
 1206,
 267553,
 200726,
 209399,
 651239,
 708309,
 679366,
 330822,
 266668,
 137809,
 500266,
 437021,
 466578,
 678095,
 682843,
 753128,
 165910,
 178325,
 577583,
 582926,
 730259,
 742498,
 540517,
 433979,
 125425,
 154051,
 409122,
 559553,
 666839,
 710019,
 739320,
 526640,
 417028,
 163860,
 223126,
 523150,
 601793,
 614682,
 690737,
 793828,
 131457,
 65387,
 105803,
 94159,
 11602,
 122192,
 176581,
 796510,
 396736,
 592084,
 298021,
 433007,
 580487,
 96179,
 334330,
 375406,
 498941,
 207533,
 207546,
 590174,
 204710,
 80431,
 105657,
 395907,
 531870,
 776719,
 595561,
 752675,
 419407,
 1384,
 509267,
 582780,
 554319,
 258517,
 296760,
 595838,
 667640,
 660024,
 718209,
 768815,
 144065,
 355290,
 458307,
 669105,
 667715,
 242799,
 424590,
 759408,
 373536,
 595319,
 647730,
 64787,
 151750,
 304250,
 743359,
 751433,
 503740,
 141515,
 643301,
 178002,
 85857,
 423660,
 530405,
 690970,
 109417,
 779367,
 538487,
 616987,
 10968,
 536912,
 289055,
 146384,
 438191,
 323259,
 525762,
 808467,
 662988,
 797456,
 102830,
 389483,
 222279,
 411239,
 468251,
 539166,
 607954,
 225949,
 248485,
 251070,
 651685,
 787490,
 63164,
 197970,
 411948,
 97984,
 545767,
 506020,
 360167,
 630910,
 631002,
 772005,
 800965,
 360654,
 531727,
 240469,
 264959,
 546562,
 698731,
 652266,
 204320,
 648634,
 279354,
 286236,
 17473,
 264235,
 7050,
 432393,
 587155,
 535735,
 414589,
 532826,
 108396,
 295342,
 410825,
 189332,
 434238,
 559484,
 307222,
 647273,
 189192,
 5812,
 128112,
 406670,
 686613,
 178514,
 229421,
 284319,
 730718,
 668552,
 212932,
 397301,
 560043,
 678944,
 689727,
 701071,
 63552,
 648674,
 487801,
 646262,
 8999,
 308270,
 229389,
 163857,
 585888,
 448300,
 693429,
 284198,
 471322,
 2340,
 64366,
 644986,
 792226,
 171406,
 257654,
 6676,
 12220,
 749977,
 420298,
 148872,
 769611,
 204508,
 762172,
 207430,
 135453,
 775727,
 62048,
 80207,
 127534,
 149552,
 167714,
 180442,
 185021,
 188409,
 189985,
 204792,
 224164,
 225391,
 232010,
 237984,
 251802,
 254467,
 283621,
 289509,
 304154,
 314059,
 361589,
 381601,
 385894,
 406104,
 425557,
 439111,
 480040,
 491637,
 566523,
 590001,
 602666,
 625482,
 694126,
 697905,
 711582,
 712783,
 753479,
 766625,
 768475,
 793136,
 796562,
 811147,
 820631,
 4629,
 388430,
 204161,
 796004,
 464402,
 544373,
 197729,
 705513,
 723879,
 391708,
 464201,
 582663,
 101363,
 235600,
 495559,
 585216,
 737628,
 741855,
 467820,
 72758,
 94765,
 296927,
 318559,
 501981,
 528465,
 556303,
 558242,
 610419,
 670825,
 705366,
 705939,
 718369,
 731029,
 421764,
 652565,
 397439,
 171496,
 404066,
 773598,
 328730,
 222305,
 516346,
 723185,
 421138,
 512137,
 293504,
 758255,
 130449,
 12913,
 73898,
 175077,
 179069,
 634611,
 650744,
 119890,
 188111,
 379231,
 672358,
 307134,
 475764,
 709808,
 180145,
 89934,
 211768,
 210290,
 775843,
 519299,
 106653,
 182220,
 63698,
 3093,
 475186,
 331184,
 580563,
 343083,
 411700,
 695715,
 792284,
 653175,
 607408,
 738277,
 409091,
 499913,
 793818,
 615915,
 686479,
 326080,
 469161,
 796859,
 221105,
 651430,
 480282,
 138984,
 240674,
 730390,
 536542,
 311311,
 732354,
 565665,
 519070,
 425984,
 570180,
 265705,
 608664,
 670329,
 700639,
 776679,
 628597,
 266901,
 758006,
 719625,
 260139,
 147173,
 163991,
 385868,
 389993,
 774780,
 216259,
 566408,
 728744,
 64294,
 121653,
 568203,
 3427,
 13663,
 15049,
 110416,
 323931,
 742491,
 529983,
 135166,
 547251,
 153800,
 384000,
 497160,
 176585,
 639220,
 86166,
 696790,
 12237,
 673311,
 10069,
 700850,
 ...]

In [13]:
filtered_df = df[df["ID"].isin(unique_id_list)]
print(len(filtered_df))
filtered_df.to_parquet("problematic_recipes.parquet", engine="pyarrow")

102096

In [14]:
remaining_df = df[~df["ID"].isin(unique_id_list)]
remaining_df.to_parquet("non-problematic_recipes.parquet", engine="pyarrow")