In [ ]:
import json
#Importing the pandas Library 
import pandas as pd

### Read Parquet File

In [ ]:
# Open and read the JSON file
with open('recipes_output.json', 'rb') as file:
    data = json.load(file)

In [154]:
data

[{'name': 'Lentil, Apple, and Turkey Wrap',
  'instructions': '1. Place the stock, lentils, celery, carrot, thyme, and salt in a  saucepan and bring to a boil. Reduce heat to low and simmer until the lentils are tender, about 30 minutes, depending on the lentils. (If they begin to dry out, add water as needed.) Remove and discard the thyme. Drain and transfer the mixture to a bowl; let cool. 2. Fold in the tomato, apple, lemon juice, and olive oil. Season with the pepper. 3. To assemble a wrap, place 1 lavash sheet on a clean work surface. Spread some of the lentil mixture on the end nearest you, leaving a 1-inch border. Top with several slices of turkey, then some of the lettuce. Roll up the lavash, slice crosswise, and serve. If using tortillas, spread the lentils in the center, top with the turkey and lettuce, and fold up the bottom, left side, and right side before rolling away from you.',
  'ingredients': [{'name': 'low-sodium vegetable or chicken stock',
    'quantity': 4.0,
    'unit': 'cups'},
   {'name': 'dried brown lentils', 'quantity': 1.0, 'unit': 'cup'},
   {'name': 'dried French green lentils', 'quantity': 0.5, 'unit': 'cup'},
   {'name': 'celery, chopped', 'quantity': 2.0, 'unit': 'stalks'},
   {'name': 'carrot, peeled and chopped', 'quantity': 1.0, 'unit': None},
   {'name': 'fresh thyme', 'quantity': 1.0, 'unit': 'sprig'},
   {'name': 'kosher salt', 'quantity': 1.0, 'unit': 'teaspoon'},
   {'name': 'tomato, cored, seeded, and diced', 'quantity': 1.0, 'unit': None},
   {'name': 'Fuji apple, cored and diced', 'quantity': 1.0, 'unit': None},
   {'name': 'freshly squeezed lemon juice',
    'quantity': 1.0,
    'unit': 'tablespoon'},
   {'name': 'extra-virgin olive oil', 'quantity': 2.0, 'unit': 'teaspoons'},
   {'name': 'Freshly ground black pepper to taste',
    'quantity': None,
    'unit': None},
   {'name': 'whole-wheat lavash, cut in half crosswise, or 6 (12-inch) flour tortillas',
    'quantity': 3.0,
    'unit': 'sheets'},
   {'name': 'turkey breast, thinly sliced', 'quantity': 0.75, 'unit': 'pound'},
   {'name': 'Bibb lettuce', 'quantity': 0.5, 'unit': 'head'}],
  'total_time': 30,
  'calories': 426.0,
  'fat': 7.0,
  'protein': 30.0,
  'desc': ''},
 {'name': 'Boudin Blanc Terrine with Red Onion Confit',
  'instructions': 'Combine first 9 ingredients in heavy  saucepan. Add 3 shallots. Bring to simmer. Remove from heat, cover and let stand 30 minutes. Chill overnight. Preheat oven to 325°F. Line 7-cup pâté or bread pan with plastic wrap. Melt butter in heavy  skillet over low heat. Add remaining 5 shallots. Cover and cook until very soft, stirring occasionally, about 15 minutes. Transfer to processor. Add pork, eggs, flour and Port and puree. Strain cream mixture, pressing on solids to extract as much liquid as possible. With processor running, add cream through feed tube and process just until combined with pork. Transfer to  bowl. Mix in currants. Spoon mixture into prepared pan. Cover with foil. Place pan in  pan. Add boiling water to larger pan to within 1/2 inch of top of terrine. Bake until terrine begins to shrink from sides of pan and knife inserted into center comes out clean, about 1 1/2 hours. Uncover and cool on rack. Chill until cold. (Can be made 3 days ahead. Cover and chill.) Line platter with lettuce. Arrange terrine atop. Sprinkle with pepper and parsley. Garnish with bay leaves. Spoon confit around sides. Serve with bread. Heat oil in heavy  skillet over -high heat. Add onions and sauté until crisp-tender, about 8 minutes. Add all remaining ingredients and stir until reduced to thick glaze, about 4 minutes. Season with salt and pepper. (Can be prepared 2 days ahead. Cover and chill.) Serve warm or at room temperature.',
  'ingredients': [{'name': 'whipping cream', 'quantity': 5.5, 'unit': 'cups'},
   {'name': 'onions, chopped', 'quantity': 2.0, 'unit': None},
   {'name': 'salt', 'quantity': 5.0, 'unit': 'teaspoons'},
   {'name': 'bay leaves', 'quantity': 3.0, 'unit': None},
   {'name': 'whole cloves', 'quantity': 3.0, 'unit': None},
   {'name': 'garlic clove, crushed', 'quantity': 1.0, 'unit': None},
   {'name': 'pepper', 'quantity': 1.0, 'unit': 'teaspoon'},
   {'name': 'ground nutmeg', 'quantity': 0.125, 'unit': 'teaspoon'},
   {'name': 'Pinch of dried thyme, crumbled', 'quantity': None, 'unit': None},
   {'name': 'shallots, minced', 'quantity': 8.0, 'unit': None},
   {'name': 'butter', 'quantity': 1.0, 'unit': 'tablespoon'},
   {'name': 'trimmed boneless center pork loin, sinew removed cut into 1-inch chunks, well chilled',
    'quantity': 1.0,
    'unit': 'pound'},
   {'name': 'eggs', 'quantity': 3.0, 'unit': None},
   {'name': 'all purpose flour', 'quantity': 6.0, 'unit': 'tablespoon'},
   {'name': 'tawny Port', 'quantity': 0.25, 'unit': 'cup'},
   {'name': 'dried currants, minced', 'quantity': 3.0, 'unit': 'tablespoons'},
   {'name': 'Lettuce leaves', 'quantity': None, 'unit': None},
   {'name': 'Cracked peppercorns', 'quantity': None, 'unit': None},
   {'name': 'Minced fresh parsley', 'quantity': None, 'unit': None},
   {'name': 'Bay leaves', 'quantity': None, 'unit': None},
   {'name': 'French bread baguette slices', 'quantity': None, 'unit': None},
   {'name': 'olive oil', 'quantity': 3.0, 'unit': 'tablespoons'},
   {'name': 'red onions, halved, sliced', 'quantity': 2.0, 'unit': None},
   {'name': 'dried currants', 'quantity': 3.0, 'unit': 'tablespoons'},
   {'name': 'red wine vinegar', 'quantity': 3.0, 'unit': 'tablespoons'},
   {'name': 'canned chicken broth', 'quantity': 1.0, 'unit': 'tablespoons'},
   {'name': 'chopped fresh thyme or 3/4 teaspoon dried, crumbled',
    'quantity': 2.0,
    'unit': 'teaspoons'},
   {'name': 'sugar', 'quantity': 0.5, 'unit': 'teaspoon'}],
  'total_time': 177,
  'calories': 403.0,
  'fat': 23.0,
  'protein': 18.0,
  'desc': 'This uses the same ingredients found in boudin blanc, the classic French white sausage. Start two days before serving.'},
 {'name': 'Potato and Fennel Soup Hodge',
  'instructions': 'In a  heavy saucepan cook diced fennel and onion in butter over moderate heat, stirring, until softened, about 10 minutes. Peel and cube potatoes. Add potatoes and broth to fennel mixture and simmer, covered, until potatoes are very tender, about 20 minutes. In a blender or food processor purée mixture in batches until smooth and return to saucepan. Stir in milk and salt and pepper to taste and simmer soup, stirring occasionally, 10 minutes, or until heated through. Garnish soup with reserved fennel leaves.',
  'ingredients': [{'name': 'fennel bulb (sometimes called anise), stalks discarded, bulb cut into 1/2-inch dice, and feathery leaves reserved for garnish',
    'quantity': 1.0,
    'unit': None},
   {'name': 'onion, diced', 'quantity': 1.0, 'unit': None},
   {'name': 'unsalted butter', 'quantity': 2.0, 'unit': 'tablespoons'},
   {'name': 'russet (baking) potatoes', 'quantity': 2.0, 'unit': None},
   {'name': 'chicken broth', 'quantity': 2.0, 'unit': 'cups'},
   {'name': 'milk', 'quantity': 5.5, 'unit': 'cups'}],
  'total_time': 40,
  'calories': 165.0,
  'fat': 7.0,
  'protein': 6.0,
  'desc': ''},
 {'name': 'Mahi-Mahi in Tomato Olive Sauce',
  'instructions': 'Heat oil in heavy  skillet over -high heat. Add onion; sauté until translucent and beginning to brown, about 4 minutes. Add wine and anchovy paste. Boil until reduced to 3/4 cup, about 3 minutes. Add tomatoes with juice; bring to boil. Sprinkle fish with salt and pepper. Add fish to skillet atop tomato mixture. Reduce heat to low, cover, and simmer until fish is cooked through, about 9 minutes. Using slotted metal spatula, transfer fish to plate and tent with foil to keep warm. Mix olives, 2 teaspoons oregano, and orange peel into sauce in skillet. Increase heat to high and boil until sauce is reduced and thickened, about 6 minutes. Season to taste with salt and pepper. Place 1 fish fillet on each of 4 plates. Pour sauce over and around fish, sprinkle with remaining 1 teaspoon oregano, and serve with warm toasted bread.',
  'ingredients': [{'name': 'extra-virgin olive oil',
    'quantity': 2.0,
    'unit': 'tablespoons'},
   {'name': 'chopped onion', 'quantity': 1.0, 'unit': 'cup'},
   {'name': 'dry white wine', 'quantity': 1.0, 'unit': 'cup'},
   {'name': 'anchovy paste', 'quantity': 1.0, 'unit': 'teaspoon'},
   {'name': '14 1/2-ounce cans diced tomatoes with garlic, basil, and oregano in juice',
    'quantity': 2.0,
    'unit': None},
   {'name': '6-ounce mahi-mahi fillets', 'quantity': 4.0, 'unit': None},
   {'name': 'green olives, quartered, pitted', 'quantity': 0.5, 'unit': 'cup'},
   {'name': 'chopped fresh oregano, divided',
    'quantity': 3.0,
    'unit': 'teaspoons'},
   {'name': '(packed) finely grated orange peel',
    'quantity': 1.0,
    'unit': 'teaspoon'},
   {'name': 'Country-style white bread cut into 1/2-inch-thick slices, toasted',
    'quantity': None,
    'unit': None}],
  'total_time': 22,
  'calories': None,
  'fat': None,
  'protein': None,
  'desc': 'The Sicilian-style tomato sauce has tons of Mediterranean flavor, thanks to the orange peel, olives, and oregano.'},
 {'name': 'Spinach Noodle Casserole',
  'instructions': 'Preheat oven to 350°F. Lightly grease 8x8x2-inch glass baking dish. Blend spinach, noodles, sour cream, pesto sauce and nutmeg in  bowl. Spoon mixture into prepared dish. Sprinkle cheese over. Bake until set, about 45 minutes. Let stand 10 minutes.',
  'ingredients': [{'name': '12-ounce package frozen spinach soufflé, thawed',
    'quantity': 1.0,
    'unit': None},
   {'name': 'extra-wide egg noodles, freshly cooked',
    'quantity': 0.5,
    'unit': 'pound'},
   {'name': 'sour cream', 'quantity': 1.0, 'unit': 'cup'},
   {'name': 'purchased pesto sauce', 'quantity': 2.0, 'unit': 'tablespoons'},
   {'name': 'ground nutmeg', 'quantity': 0.25, 'unit': 'teaspoon'},
   {'name': 'grated sharp cheddar cheese', 'quantity': 1.0, 'unit': 'cup'}],
  'total_time': 55,
  'calories': 547.0,
  'fat': 32.0,
  'protein': 20.0,
  'desc': ''},
 {'name': 'The Best Blts',
  'instructions': 'Mix basil, mayonnaise and butter in processor until basil is finely chopped and mixture is well blended. Season to taste with salt and pepper. (Can be made 1 day ahead. Cover and refrigerate.) Cook bacon in heavy  skillet over -high heat until crisp, about 8 minutes. Transfer to paper towels; drain. Spread half of mayonnaise mixture over 1 side of 6 bread slices. Top each with 2 tomato slices. Sprinkle tomatoes with salt and pepper. Top tomato slices with avocado, then with bacon strips, onion and lettuce. Spread remaining mayonnaise mixture over remaining 6 bread slices. Place bread slices atop lettuce. Cut sandwiches in half and serve.',
  'ingredients': [{'name': '(lightly packed) fresh basil leaves',
    'quantity': 10.5,
    'unit': 'cups'},
   {'name': 'mayonnaise', 'quantity': 1.0, 'unit': 'cup'},
   {'name': 'butter, room temperature', 'quantity': 0.25, 'unit': 'cup'},
   {'name': 'thick-sliced bacon strips (about 1 pound)',
    'quantity': 12.0,
    'unit': None},
   {'name': '12 1/2-inch-thick slices fresh country-style white bread',
    'quantity': None,
    'unit': None},
   {'name': 'tomatoes, cut into 1/4-inch-thick rounds',
    'quantity': 3.0,
    'unit': None},
   {'name': 'ripe avocados, pitted, peeled, sliced',
    'quantity': 2.0,
    'unit': None},
   {'name': 'red onion, thinly sliced', 'quantity': 1.0, 'unit': None},
   {'name': 'lettuce leaves', 'quantity': 6.0, 'unit': None}],
  'total_time': 8,
  'calories': 948.0,
  'fat': 79.0,
  'protein': 19.0,
  'desc': 'This recipe can be prepared in 45 minutes or less.'},
 {'name': 'Ham and Spring Vegetable Salad with Shallot Vinaigrette',
  'instructions': 'Cook potatoes and carrots in  pot of boiling salted water until almost tender, about 7 minutes. Add asparagus and peas; cook until vegetables are just tender, about 3 minutes longer. Drain. Rinse with cold water; drain. Transfer to  bowl. (Can be prepared 1 day ahead. Cover; chill.) Add ham to vegetables. Add Shallot Vinaigrette to salad and toss to coat. Season to taste with salt and pepper. Line bowl with spinach. Top with salad and serve.',
  'ingredients': [{'name': 'red-skinned potatoes, each cut into 8 wedges',
    'quantity': 5.5,
    'unit': 'pounds'},
   {'name': 'baby carrots, peeled, cut lengthwise in half',
    'quantity': 5.5,
    'unit': 'pounds'},
   {'name': 'asparagus, trimmed, cut into 2-inch pieces',
    'quantity': 5.5,
    'unit': 'pounds'},
   {'name': 'sugar snap peas, trimmed', 'quantity': 6.0, 'unit': 'ounces'},
   {'name': 'low-fat (97% fat-free) smoked ham, cut into 1/4-inch-thick slices, then into 2-inch-long by 1/2-inch-wide pieces',
    'quantity': 18.0,
    'unit': 'ounces'},
   {'name': 'Shallot Vinaigrette', 'quantity': None, 'unit': None},
   {'name': '6-ounce package fresh baby spinach',
    'quantity': 1.0,
    'unit': None}],
  'total_time': 10,
  'calories': None,
  'fat': None,
  'protein': None,
  'desc': 'Serve this newfangled main-course salad with a crisp flatbread, such as lavash, and white wine or rosé spritzers.'},
 {'name': 'Spicy-Sweet Kumquats',
  'instructions': 'Stir together sugar and chili powder. Whisk egg whites with water until dissolved. Working with 1 kumquat at a time, dip 1 side in whites, letting excess drip off, then dip in sugar mixture. Transfer to a rack to dry, coated side up.',
  'ingredients': [{'name': 'granulated sugar',
    'quantity': 6.0,
    'unit': 'tablespoons'},
   {'name': 'chili powder', 'quantity': 5.5, 'unit': 'tablespoons'},
   {'name': "powdered egg whites (see Cooks' notes)",
    'quantity': 4.0,
    'unit': 'teaspoons'},
   {'name': 'warm water', 'quantity': 0.25, 'unit': 'cup'},
   {'name': 'kumquats (preferably thin-skinned)',
    'quantity': 60.0,
    'unit': None}],
  'total_time': None,
  'calories': None,
  'fat': None,
  'protein': None,
  'desc': 'Pop one of these in your mouth for a burst of bittersweet flavor.'},
 {'name': 'Korean Marinated Beef',
  'instructions': 'Stir together soy sauce, sugar, sesame oil, white and pale green scallions, garlic, ginger, and 2 tablespoons sesame seeds in a bowl until sugar is dissolved. Add steak and toss to coat, then marinate 15 minutes. Heat vegetable oil in a 12-inch heavy skillet over high heat until just smoking, then add steak in 1 layer and sauté, turning over occasionally, until browned and just cooked through, about 5 minutes total. Transfer to a platter and sprinkle with scallion greens and remaining 1 tablespoon sesame seeds, then serve with accompaniments. *Available at Asian markets and many supermarkets.',
  'ingredients': [{'name': 'soy sauce', 'quantity': 0.25, 'unit': 'cup'},
   {'name': 'sugar', 'quantity': 1.0, 'unit': 'tablespoon'},
   {'name': 'Asian sesame oil', 'quantity': 2.0, 'unit': 'teaspoons'},
   {'name': 'scallions (white and pale green parts separated from greens), minced (1/2 cup)',
    'quantity': 1.0,
    'unit': 'bunch'},
   {'name': 'minced garlic', 'quantity': 1.0, 'unit': 'tablespoon'},
   {'name': 'minced peeled fresh ginger',
    'quantity': 1.0,
    'unit': 'tablespoon'},
   {'name': 'sesame seeds, toasted', 'quantity': 3.0, 'unit': 'tablespoons'},
   {'name': 'flank steak, cut across the grain into very thin slices (no more than 1/8 inch thick)',
    'quantity': 1.0,
    'unit': 'lb'},
   {'name': 'vegetable oil', 'quantity': 1.0, 'unit': 'tablespoon'},
   {'name': 'Accompaniments: butter lettuce or other soft-leaf lettuce; thinly sliced garlic; packaged kimchi*; steamed white rice',
    'quantity': None,
    'unit': None}],
  'total_time': 20,
  'calories': 170.0,
  'fat': 10.0,
  'protein': 7.0,
  'desc': 'Bulgogi'},
 {'name': 'Ham Persillade with Mustard Potato Salad and Mashed Peas',
  'instructions': 'Chop enough parsley leaves to measure 1 tablespoon; reserve. Chop remaining leaves and stems and simmer with broth and garlic in a  saucepan, covered, 5 minutes. Meanwhile, sprinkle gelatin over water in a  bowl and let soften 1 minute. Strain broth through a fine-mesh sieve into bowl with gelatin and stir to dissolve. Season with salt and pepper. Set bowl in an ice bath and cool to room temperature, stirring. Toss ham with reserved parsley and divide among jars. Pour gelatin on top and chill until set, at least 1 hour. Whisk together mayonnaise, mustard, vinegar, 1/4 teaspoon salt, and 1/4 teaspoon pepper in a  bowl. Stir in celery, cornichons, and potatoes. Pulse peas with marjoram, oil, 1/2 teaspoon pepper, and 1/4 teaspoon salt in a food processor to a coarse mash. Layer peas, then potato salad, over ham.',
  'ingredients': [{'name': 'long parsley sprigs, divided',
    'quantity': 6.0,
    'unit': None},
   {'name': 'reduced-sodium chicken broth', 'quantity': 3.25, 'unit': 'cups'},
   {'name': 'garlic clove, minced', 'quantity': 1.0, 'unit': None},
   {'name': 'unflavored gelatin (from 1 envelope)',
    'quantity': 2.0,
    'unit': 'teaspoon'},
   {'name': 'water', 'quantity': 3.0, 'unit': 'tablespoons'},
   {'name': '(3/4-pound) piece baked ham, cut into 1/2-inch cubes (2 cups)',
    'quantity': 1.0,
    'unit': None},
   {'name': 'mayonnaise', 'quantity': 0.5, 'unit': 'cup'},
   {'name': 'Dijon mustard', 'quantity': 2.0, 'unit': 'tablespoons'},
   {'name': 'white-wine vinegar', 'quantity': 2.0, 'unit': 'tablespoons'},
   {'name': 'celery ribs, finely chopped (1 cup)',
    'quantity': 2.0,
    'unit': None},
   {'name': 'chopped cornichons or sour gherkins',
    'quantity': 0.25,
    'unit': 'cup'},
   {'name': 'boiled potatoes, peeled and cut into 1/2-inch cubes (2 1/2 cups)',
    'quantity': 1.0,
    'unit': 'pound'},
   {'name': '(10-ounce) box frozen baby peas, thawed',
    'quantity': 1.0,
    'unit': None},
   {'name': 'finely chopped marjoram', 'quantity': 2.0, 'unit': 'teaspoons'},
   {'name': 'extra-virgin olive oil', 'quantity': 3.0, 'unit': 'tablespoons'},
   {'name': 'Equipment: 4 (16-ounce) wide jars or containers with lids',
    'quantity': None,
    'unit': None},
   {'name': 'Garnish: celery leaves', 'quantity': None, 'unit': None}],
  'total_time': 66,
  'calories': 602.0,
  'fat': 41.0,
  'protein': 23.0,
  'desc': 'Transform your picnic into un pique-nique to remember with this elegant arrangement of tangy potato salad, peas gently mashed with marjoram, and salty ham softly set in parsleyed gelatin.'},
 {'name': 'Yams Braised with Cream, Rosemary and Nutmeg',
  'instructions': 'Heat oil in heavy  skillet over -high heat. Add shallots and minced rosemary and sauté until tender, about 3 minutes. Add yams and broth to skillet and bring to boil. Cover skillet, reduce heat to -low and simmer until yams are almost tender, about 10 minutes. Add cream and sprinkle lightly with nutmeg. Simmer uncovered until yams are very tender and liquid thickens and coats yams, about 4 minutes. Season with salt and pepper. (Can be made 1 day ahead. Transfer to microwave-safe dish. Chill until cold, then cover and keep chilled. Rewarm, covered, in microwave on -low heat.)',
  'ingredients': [{'name': 'olive oil', 'quantity': 4.0, 'unit': 'teaspoons'},
   {'name': 'finely chopped shallots', 'quantity': 0.5, 'unit': 'cup'},
   {'name': 'minced fresh rosemary', 'quantity': 10.5, 'unit': 'teaspoons'},
   {'name': 'yams (red-skinned sweet potatoes), peeled, cut into 1/2-inch-thick rounds, rounds cut in half',
    'quantity': 3.0,
    'unit': 'pounds'},
   {'name': 'canned low-salt chicken broth', 'quantity': 2.75, 'unit': 'cups'},
   {'name': 'whipping cream', 'quantity': 0.5, 'unit': 'cup'},
   {'name': 'Ground nutmeg', 'quantity': None, 'unit': None}],
  'total_time': 17,
  'calories': 256.0,
  'fat': 5.0,
  'protein': 4.0,
  'desc': 'Simmering the yams fills them with flavor and yields a lovely coating.'},
 {'name': 'Spicy Noodle Soup',

In [155]:
# Convert to a DataFrame
df = pd.json_normalize(data)

# Create a new column 'ingredient_names' that contains a list of ingredient names
df['ingredient_names'] = df['ingredients'].apply(lambda ingredients: [ingredient['name'] for ingredient in ingredients])

# Drop the original 'ingredients' column if you only need the list of names
df = df.drop(columns=['ingredients'])
df = df.drop(columns=['calories'])
df = df.drop(columns=['fat'])
df = df.drop(columns=['protein'])
df = df.drop(columns=['desc'])

In [157]:
df.columns

Index(['name', 'instructions', 'total_time', 'ingredient_names'], dtype='object')

In [158]:
df['name'] = df['name'].str.replace('"', '', regex=False)

In [159]:
def count_empty_ingredient_lists(df):
    # Count the number of empty lists in the 'ingredient_names' column
    empty_list_count = df['ingredient_names'].apply(lambda x: x == []).sum()
    return empty_list_count

In [160]:
count_empty_ingredient_lists(df)

76

In [161]:
def remove_empty_ingredient_rows(df):
    # Filter out rows where 'ingredient_names' is an empty list
    filtered_df = df[df['ingredient_names'].apply(lambda x: len(x) > 0)]
    return filtered_df

In [162]:
filtered_df = remove_empty_ingredient_rows(df)

In [163]:
filtered_df

,name,instructions,total_time,ingredient_names
0,"Lentil, Apple, and Turkey Wrap","1. Place the stock, lentils, celery, carrot, t...",30.0,"[low-sodium vegetable or chicken stock, dried ..."
1,Boudin Blanc Terrine with Red Onion Confit,Combine first 9 ingredients in heavy saucepan...,177.0,"[whipping cream, onions, chopped, salt, bay le..."
2,Potato and Fennel Soup Hodge,In a heavy saucepan cook diced fennel and oni...,40.0,"[fennel bulb (sometimes called anise), stalks ..."
3,Mahi-Mahi in Tomato Olive Sauce,Heat oil in heavy skillet over -high heat. Ad...,22.0,"[extra-virgin olive oil, chopped onion, dry wh..."
4,Spinach Noodle Casserole,Preheat oven to 350°F. Lightly grease 8x8x2-in...,55.0,"[12-ounce package frozen spinach soufflé, tha..."
...,...,...,...,...
20125,Parmesan Puffs,Beat whites in a bowl with an electric mixer u...,3.0,"[egg whites, Parmigiano-Reggiano, finely grate..."
20126,Artichoke and Parmesan Risotto,Bring broth to simmer in saucepan.Remove from ...,41.0,"[(or more) low-salt chicken broth, butter, div..."
20127,Turkey Cream Puff Pie,"Using a sharp knife, cut a shallow X in bottom...",67.0,"[tomato, onion, finely chopped (1/2 cup), unsa..."
20128,Snapper on Angel Hair with Citrus Cream,Heat 2 tablespoons oil in heavy skillet over ...,14.0,"[olive oil, shallots, thinly sliced (about 1/2..."
20129,Baked Ham with Marmalade-Horseradish Glaze,Position rack in bottom third of oven and preh...,150.0,"[18-pound fully cooked bone-in smoked ham, roo..."

In [167]:
def remove_duplicates_by_column(df, column):
    # Identify exact duplicate rows based on the 'name' column
    exact_duplicates = df[df.duplicated(subset=column, keep=False)]
    
    # Print the exact duplicates
    print(f"Exact duplicate rows based on {column}:")
    print(exact_duplicates)
    
    # Remove exact duplicates based on the 'name' column, keeping only the first occurrence
    filtered_df = df.drop_duplicates(subset=column, keep='first')
    
    return filtered_df

In [ ]:
filtered_df_name = remove_duplicates_by_column(df, 'name')

Exact duplicate rows based on name:
                                                    name  \
14                                         Peach Mustard
17                           Crisp Braised Pork Shoulder
21                                         Fried Chicken
24                               Sea Salt-Roasted Pecans
25                                Garlic Baguette Crumbs
27                                     Dried Pear Crisps
31                       Moroccan-Style Preserved Lemons
36           Pastry Twists with Spiced Sugar-Honey Glaze
37                                 Sauteed Broccoli Rabe
39                          Better-Than-Pita Grill Bread
43                         Purple-Potato and Crab Gratin
45                                    Pickled Red Onions
57                                       Pumpkin Muffins
58                                 Orange Balsamic Glaze
62     Southwest Corn Bread Stuffing with Corn and Gr...
67                                   Italian Vinaigrette
90     Carrot, Snow Pea, and Red Pepper Julienne in H...
95                                          Parsley Mayo
96            Acini di Pepe Pasta with Garlic and Olives
100                                      Shrimp Gazpacho
102                               Parsnip and Apple Soup
106                                    Garlic Bruschetta
108                              Sausage Fennel Stuffing
111                          Honey-Ginger Barbecue Sauce
118                           Blackberry-Raspberry Sauce
121          Roast Cod with Potatoes, Onions, and Olives
122                                   Spicy Tomato Sauce
123    Cod Cannelloni with Swiss Chard and Roasted Pe...
124                      Swiss Chard with Roasted Pepper
126                                         Pastry Dough
130                    Country Sausage and Sage Dressing
131                           Cherry Lime Virgin Rickeys
132                          Buttermilk-Spinach Spaetzle
136                                Low-Fat Chicken Stock
137                                  Honey Mustard Sauce
139                                  Asian Dipping Sauce
144                              Roasted Root Vegetables
145                                      Thai Vegetables
156                                    Lemon Vinaigrette
166                           Sauteed Fennel and Carrots
167       Grilled Garlic-Marinated Skirt Steak with Lime
168          Miniature Crab Cakes with Tomato Ginger Jam
170         Red Wine Brasato with Glazed Root Vegetables
171                                           Tomato Jam
172                      Egg Salad with Lemon and Fennel
185                              Homemade Tomato Ketchup
189                               Seasoned Nori Wrappers
191    Chocolate Hazelnut Pound Cake with Chocolate G...
192                                Tarragon Tartar Sauce
204                        Chicken and Sausage Jambalaya
214                    Kale with Sauteed Apple and Onion
218                                               Eggnog
222                           Cherry Cola Barbecue Sauce
223                                  Golden Turkey Stock
229                           Blackberry-Raspberry Sauce
231                 Mashed Potato and Cauliflower Gratin
237                                   Green Olive Relish
250                                 Sour Cream Apple Pie
264                   Cold Noodle Salad with Ponzu Sauce
267                                     Sanuki Sea Stock
268                           To Cook Dried Udon Noodles
281                                     Fish Mixed Grill
285                             Salted Water for Boiling
291                                          Lamb Steaks
292                                        Chicken Stock
293                                   Quick Tartar Sauce
299                                    Tequila Lime Tart
303                                 Summer Squash Sauté
309    Toasted Almond Cream Pie with Boysenberry Topping
311                                Habanero-Orange Salsa
312    Butterflied Turkey with Fennel, Sausage, and R...
316                             Light Lemon Yogurt Sauce
320                                   Fresh Tomato Salsa
339                                          Sticky Rice
340                               Seasoned Nori Wrappers
345    Sweet-Potato Gaufrettes with Duck Confit and C...
352                                Champagne Vinaigrette
356                                            Cassoulet
357           Vanilla Mousse Meringues and Fresh Berries
359                                          Duck Confit
361                              Toasted Baguette Crumbs
363                                   Spiced Pita Toasts
364                                    House Vinaigrette
365                                       Court Bouillon
373                                           Veal Stock
374                                          Orange Dust
375                            Café Azul's Pastry Dough
385                          Whipped Potatoes with Herbs
386                                      Jalapeño Agave
391                                      Parsnip Gnocchi
392                                         Toffee Sauce
398                                Basic Mashed Potatoes
404    Smoked Chicken Salad on Toasted Corn Bread Tri...
407                    Buttered New Potatoes with Chives
408                            Candied Grapefruit Strips
417                                 Chicken Tikka Masala
419    Lemon Cornmeal Cake with Lemon Glaze and Crush...
420                              Amaretto Olive Oil Cake
424                                 Blue Cheese Coleslaw
427                                     Caramelized Nuts
430                                           Fish Tacos
442                            Ginger-Cream Cheese Icing
445                                           Date Paste
446                     Banana-Pineapple Yogurt Smoothie
450                                  Cucumber Sour Cream
455    Grilled Chicken with Goat Cheese Stuffing, Pep...
456                             Jalapeño-Cilantro Salsa
464                                        Arugula Pesto
471    Cheese- and Shrimp-Stuffed Roasted Poblanos wi...
474                             Corn and Lobster Chowder
476             Brown Rice Pilaf with Saffron and Ginger
504                                   Roasted Vegetables
507                                       Tomato Chutney
511    Grilled Tri-Tip Roast with Tequila Marinade an...
521                                   Spiced Pita Toasts
528                                          Bee's Knees
532                       Grandmother Walters's Biscuits
533                                        Oeufs Au Plat
539                                Sofrito Grilled Bread
541           Blue Lake Green Beans with Lemon and Thyme
548                                          Moscow Mule
551                            Roasted Garlic-Herb Sauce
554    Sausage, Bell Pepper, and Onion Focaccia Sandw...
570                           Ancho-Guajillo Chile Sauce
580                                    Cebollitas Asadas
581                                   Frijoles Borrachos
583    Grilled Tuna and Roasted Pepper Sandwiches on ...
585              Potato Gratin with White Cheddar Cheese
586                               True Vanilla Ice Cream
600                       Cranberry Black Pepper Chutney
602                                Orange Balsamic Glaze
604                                    Chimichurri Sauce
605                                Buttery Sugar Cookies
607                                Peach and Apple Salsa
609                                     Red Pepper Sauce
616                                              Za'atar
621                              Creamed Corn with Bacon
624                                              Fajitas
628                                    Bloody Mary Aspic
629           Cold-Smoked Chicken Legs in a Chinese Cure
634                         Leftover-Roast-Chicken-Stock
638       Buttermilk Ice Cream with Spiced Fruit Compote
640    Coffee and Turron Ice Cream Torte with Honey-B...
651    Raspberry-Apricot Compote with Champagne and L...
652                                    Pistachio Brittle
654                             Reheating Corn Tortillas
657                                  Coconut-Curry Sauce
662                        Tarragon-Cilantro Salsa Verde
670                                    Coriander Chutney
671            Szechuan-Flavored Country-Style Spareribs
672                                     Blackberry Syrup
683                             Golden Pineapple Chutney
684    Thick White Noodles in Soup, Topped with Eggs ...
687                          To Toast and Skin Hazelnuts
698                                Apricot Caramel Sauce
709                                             Blatjang
710                                           Celery Duo
711    Daniel Boulud's Short Ribs Braised in Red Wine...
713                                              Bobotie
718                               Garlic Baguette Crumbs
720                                            Ham Stock
723                                      Beef Bone Broth
731    Grilled Tea-Brined Turkey with Tea-and-Lemon G...
733                                   Smoky Tomato Sauce
735                       Lime, Garlic, and Oregano Mojo
752        Cauliflower-Leek Kugel with Almond-Herb Crust
753                                        Classic Pesto
754                                  Turkey Giblet Stock
757                                           Hot Browns
766    Bo Ssäm Grilled Pork and Pickled Slaw in Lett...
769                               Garlic Mashed Potatoes
771                                         Turkey Stock
773                          To Toast and Skin Hazelnuts
785                                          Lemon Cream
787            Roasted Root Vegetables with Green Onions
794                                           Mint Julep
795                                    Horseradish Cream
796                                Maple Granola Brittle
797                            Apple Galette with Orange
799           Clementine-Salted Turkey with Redeye Gravy
805               Seafood Salad with Collard Greens Slaw
806                             Golden Pineapple Chutney
807                                        Chicken Stock
821                         Spiced Wine with Dried Fruit
825                                          Yellow Rice
835                                    Lemon Vinaigrette
836                                 Balsamic Vinaigrette
837                                Pappardelle Bolognese
839                     Arugula with Lemon and Olive Oil
841    Steamed Scallion Ginger Fish Fillets with Bok ...
845                                 Black Pepper Almonds
846                                          Greek Salad
848                                 Apple Ginger Chutney
854                                        Mexican Crema
855                  Red, White, and Blue Ice Cream Cake
860                                     Eggnog Ice Cream
861                                        Vanilla Sugar
863                              Pineapple-Avocado Salsa
864                                Basic Cranberry Sauce
867                                 Balsamic Vinaigrette
870                                          Fudge Sauce
873                                     Basic Duck Stock
875                                         Deviled Eggs
877                                          Puff Pastry
881                         Roasted Garlic Cheese Toasts
883                                Herbed Oyster Crakers
887                                        Coconut Sauce
890           Grass-Fed Beef Meatloaf in a Bacon Blanket
894                                       Vinegared Rice
900                            Butter Shortbread Cookies
901                                   Classic Shortbread
902                                Five-Spice Shortbread
903                   Double Chocolate-Ginger Shortbread
904                         Caramel Macadamia Nut Crunch
913                                   Blender Mayonnaise
916            Barbecued Turkey with Maple-Mustard Glaze
917                             Vegetable and Bean Chili
923                          Barba Yianni's Grilled Lamb
941                                            French 75
943                                   Roasted Vegetables
946                                        Custard Sauce
947                               Buttermilk Spoon Bread
957                                  Turkey Giblet Stock
973       Pear Charlottes with Chamomile Crème Anglaise
977                                 Lemongrass Consommé
978                                   Fresh Tomato Sauce
989                                     Tropical Sundaes
992                                      Rutabaga Purée
993    Rib-Eye Steaks with Roasted Red Peppers and Ba...
994                                       Parmesan Sauce
1002                                   Asparagus Risotto
1005             Black-Bean Shrimp with Chinese Broccoli
1008                                         Juicy Bella
1011                                               Dashi
1013                               Grilled Tandoori Lamb
1015   Carrot Cake with Cream Cheese-Lemon Zest Frosting
1016                                   Thai Summer Rolls
1017                                  Spiced Chili Sauce
1020                             Roasted Root Vegetables
1027                                Almond Butter Crisps
1034                                Tandoori Spice Blend
1035   Spice-Rubbed Duck Legs Braised with Green Oliv...
1039                               Heirloom Tomato Salad
1040   Vanilla-Bean Cheesecake with Guava Topping and...
1041                         Salted Brown Butter Cookies
1043   Grilled Beef Tenderloin with Roasted Garlic Sa...
1048                Red-Cooked Pork with Frizzled Ginger
1050                                  Homemade Grenadine
1054                                     Ginger Ice Milk
1055                                 Chestnut Cheesecake
1069                                         Puff Pastry
1076                                             Unknown
1079                     To Toast Spices, Nuts, or Seeds
1082                                        Pastry Dough
1085                                   Chile Lime Tuiles
1091                                         Pizza Dough
1095                                           Gremolata
1096                           Curried Pineapple Chutney
1097                                         Salsa Verde
1100                          Roasted-Garlic Vinaigrette
1101                                   Chocolate Sabayon
1105                                Szechuan Salt-Pepper
1107                         Horseradish Mashed Potatoes
1108          Garlic and Herb Spatchcock Grilled Chicken
1109                                 Sweet Mustard Sauce
1115                         Roast Goose with Port Gravy
1121                                Blue Cheese Coleslaw
1122                                            Haroseth
1125                                              Tongue
1126                                  Mexican White Rice
1128     Herb Salad Spring Rolls with Spicy Peanut Sauce
1132                   Potato, Apple, and Prune Stuffing
1135                                             Unknown
1136                                    Lemon-Mint Sauce
1141                        Caramel Macadamia Nut Crunch
1152                           Roasted Winter Vegetables
1153   Toasted Almond Cream Pie with Boysenberry Topping
1154                           Apple and Tart Cherry Pie
1155                           Cream Cheese Pastry Dough
1159                                  Quick Turkey Stock
1162                                Tropical Fruit Salsa
1167            Roasted Beef Tenderloin Wrapped in Bacon
1168                  Roasted Root Vegetable Vinaigrette
1174                               Sweet Chocolate Glaze
1178                                       Avocado Cream
1179                                Strawberry Ice Cream
1180                                        Pastry Dough
1187                                       Chicken Stock
1214            Apple Crisp with Prune Tequila Ice Cream
1224                      Orange, Radish and Olive Salad
1236                              Sauteed Collard Greens
1237                                 Candied Citrus Peel
1240                          Spiced Pear and Raisin Pie
1241   Pineapple, Apricot and Cranberry Lattice-Crust...
1242                             Honey-Pecan Pumpkin Pie
1248                                Coconut Chicken Soup
1250                                          Pan Bagnat
1254                                        Pastry Dough
1258                                Prepared Horseradish
1263                             Cottage Cheese Pancakes
1266            Roasted Beef Tenderloin Wrapped in Bacon
1267                        Sweet & Tangy Barbecue Sauce
1271   Grilled Pork Kebabs with Ginger Molasses Barbe...
1275                         Vanilla and Almond Frosting
1277            Chocolate-Strawberry-Orange Wedding Cake
1289                                          Irish Stew
1292                                        Peanut Sauce
1304                             Homemade Ricotta Cheese
1306                        Cilantro Garlic Yogurt Sauce
1307                                      Chicken Kebabs
1308          Rice Pilaf with Lamb, Carrots, and Raisins
1310   Green Olive, Lemon, and Garlic-Roasted Leg of ...
1316                                   Flemish Beef Stew
1324                     Grilled Swedish Meatball Kebabs
1333                                Five-Spice Ice Cream
1335                        Raspberry Champagne Cocktail
1341                   Whole Wheat Sun-Dried Tomato Buns
1343                                 Chipotle Mayonnaise
1345                             Lime-Pickled Red Onions
1347                                 Winter Tomato Sauce
1349                  Sausage and Broccoli Rabe Frittata
1354                                       Basic Brioche
1363                    Spanish White Beans with Spinach
1368                                 Blueberry Ice Cream
1371                 To Quick-Soak Dried Black-Eyed Peas
1375   Saffron Chicken Breasts with English Pea Puré...
1381                           Black Bean and Rice Salad
1383                                           French 75
1384                                      Sauce Ravigote
1395                           Pork Tenderloin Churrasco
1397                              Chocolate-Cognac Cream
1399                          Moroccan-Spiced Vegetables
1400                             Creamed Corn with Bacon
1401                              Basic Buckwheat Crepes
1403                                              Tongue
1415                           Chocolate-Dipped Cherries
1420                                           Guacamole
1423                             Pumpkin Cranberry Bread
1430                   Cabbage and Bacon Mashed Potatoes
1434                                          Mint Julep
1436   Thick White Noodles in Soup, Topped with Eggs ...
1443                                  Saffron Mayonnaise
1444                                      Scrambled Eggs
1446                             Indian Clarified Butter
1451                             Ginger-Cilantro Chutney
1455                                        Pastry Cream
1460                               Homemade Curry Powder
1464                                  Sesame Vinaigrette
1469                              Manhattan Clam Chowder

In [169]:
filtered_df_name

,name,instructions,total_time,ingredient_names
0,"Lentil, Apple, and Turkey Wrap","1. Place the stock, lentils, celery, carrot, t...",30.0,"[low-sodium vegetable or chicken stock, dried ..."
1,Boudin Blanc Terrine with Red Onion Confit,Combine first 9 ingredients in heavy saucepan...,177.0,"[whipping cream, onions, chopped, salt, bay le..."
2,Potato and Fennel Soup Hodge,In a heavy saucepan cook diced fennel and oni...,40.0,"[fennel bulb (sometimes called anise), stalks ..."
3,Mahi-Mahi in Tomato Olive Sauce,Heat oil in heavy skillet over -high heat. Ad...,22.0,"[extra-virgin olive oil, chopped onion, dry wh..."
4,Spinach Noodle Casserole,Preheat oven to 350°F. Lightly grease 8x8x2-in...,55.0,"[12-ounce package frozen spinach soufflé, tha..."
...,...,...,...,...
20124,Chinese Barbecued Spareribs,Wash spareribs. Remove excess fat and gristle....,30.0,"[side pork spareribs, about 3 pounds, soy sauc..."
20126,Artichoke and Parmesan Risotto,Bring broth to simmer in saucepan.Remove from ...,41.0,"[(or more) low-salt chicken broth, butter, div..."
20127,Turkey Cream Puff Pie,"Using a sharp knife, cut a shallow X in bottom...",67.0,"[tomato, onion, finely chopped (1/2 cup), unsa..."
20128,Snapper on Angel Hair with Citrus Cream,Heat 2 tablespoons oil in heavy skillet over ...,14.0,"[olive oil, shallots, thinly sliced (about 1/2..."
20129,Baked Ham with Marmalade-Horseradish Glaze,Position rack in bottom third of oven and preh...,150.0,"[18-pound fully cooked bone-in smoked ham, roo..."

In [172]:
filtered_df_all = remove_duplicates_by_column(filtered_df_name, 'instructions')

Exact duplicate rows based on instructions:
                                                    name  \
137                                  Honey Mustard Sauce
348                           Strawberry Banana Smoothie
453                                   Ginger Spice Syrup
527                                                 Tago
528                                          Bee's Knees
547                                        Blue Mountain
577                                      Orange Gin Fizz
590                                             Affinity
758                                          Margarita I
770                                         Moulin Rouge
951                                 Mixed-Berry Daiquiri
1076                                             Unknown
1453                           Barley and Mushroom Pilaf
1466                                   Maiden's Prayer I
1484                             Mozzarella Pesto Spread
1602                                          Sandmartin
1659                                          Piccadilly
1796                                         Hotel Plaza
1959                                      Fine and Dandy
2254                   Pizza 6: Pan-fried Hawaiian Pizza
2354                            Vietnamese Dipping Sauce
2540                                       Old-Fashioned
2596                                      Highland Fling
2677                                              Quaker
2692   Watermelon and Feta With Lime and Serrano Chil...
2725              Asian Lamb Stir-Fry in Radicchio Wraps
2835                                               Bronx
2847                                        Mulled Cider
2963                         Ginger Stinger or White Way
3019                                    Polly (or Poppy)
3055                                          Bushranger
3294                                    Mixed Herb Pesto
3672          Strawberry-Watermelon Smoothie with Ginger
3746                               Creamy Basil Dressing
3800                                         Chanticleer
3926                             Bunny Hug or Earthquake
3945                                                Buby
3972                                            Rum Fizz
4029                                             Maurice
4156                                  Coctel Veracruzana
4424                                         Kingston II
4450                    Passion Fruit Champagne Cocktail
4475                                             Sputnik
4656                                          White Lion
4950                                              Gilroy
5017                                            Shanghai
5030                                       Yellow Parrot
5102                                                Love
5126                                     Bachelor's Bait
5673                                     Alexander Young
5849                    Peanut Butter and Grape Smoothie
5851                                              Allies
5942                                      Million Dollar
5982                                     Mule's Hind Leg
6148                                         Silver King
6248                           Pineapple-Banana Smoothie
6305                                           Alexander
6578                                          Pink Rosé
6706                                           Cuban III
6816                                       Blue Hawaiian
6927                                         Fuzzy Navel
7072                                    Passion Daiquiri
7091                                    Sex on the Beach
7200                            Bronx Silver or Oriental
7365                                          Plum Glaze
7425                                 Apricot Cocktail II
7467                                              Caruso
7572                                          Journalist
8024                                        Johnnie Mack
8042                                           Margarita
8154                              Mango Frozen Margarita
8215                                      Merry Widow II
8290                                               Royal
8345                                Tomato-Onion Topping
8394                                  Brandy Alexander I
8689                                         Loudspeaker
8870                                        Third Degree
9040                                           Bulldog I
9215                                              Robson
9291                                           Mainbrace
9593                    Passion-Fruit Champagne Cocktail
9882                               Blackberry Kir Royale
9916                                           Apple Pie
10210                                           Fig Leaf
10287                                            Cornell
10512                                 Damn the Weather I
10613                                              Hasty
10649                               Carrot Cake Smoothie
10658                                              Peggy
10761                                            Liberty
10939                                     Cameron's Kick
11015                                              Dixie
11104                                             Barnum
11195                             Whispers of the Forest
11317                                       Froth Blower
11479                                       Papaya Salsa
11508                                       Eye Opener I
11673                                           Favortie
12004                                            Thistle
12124                              Frozen Mango Daiquiri
12330                                          Honeymoon
12378                                            Elegant
12382                                               Pope
12388                                        Hawaiian II
12454                                           Paradise
12493                                       Bronx Golden
12530        Cheddar, Red Pepper, and Horseradish Spread
12993                                          Ruby Fizz
13021                                               Bolo
13066                                            Xanthia
13093                                        Fairy Belle
13110                                         Archbishop
13135                                           Napoleon
13165                                     Leave It to Me
13374                                       Three Miller
13526                                             Adonis
13627                                               Opal
13851                                     Prince's Smile
14071                                     Mother Sherman
14288                                         Rustic Rub
14355                                       Jamaica Glow
14376                                           Honolulu
14481                                        Hole in One
14578                                          Nightmare
14614                                     Café de Paris
14619                                              Davis
14664                                             Ulanda
14763                              Cilantro-Tomato Salsa
14890                                              Opera
14965                                         Ladyfinger
15022                                           Hawaiian
15499                                     Golden Slipper
15649                                    Chelsea Sidecar
15684                                      Three Stripes
15752                                            Bennett
15774                                Imperial Hotel Fizz
15778                                             Modern
15835                                         Hawaiian I
15907                                  Deluxe Kir Royale
15914                                 Citrus Spice Syrup
16014                                 Queen Elizabeth II
16135                        Mocha Berry-Almond Smoothie
16405                                      Bermuda Rosé
16745                                         Millionire
16885                                       Little Devil
16934                                    Bacardi Special
16985                                           Festival
17044                                    Pernod Cocktail
17101                                   El Presidente II
17160          Frozen Banana, Pineapple and Rum Cocktail
17198                   Mango and Passion Fruit Smoothie
17248                                        Clover Club
17478                                           Sloe Gin
17522                           Strawberry Prosecco Soup
17649                                       Emerald Isle
17851  Watermelon and Feta with Lime and Serrano Chil...
17908         Blueberry-Beet Smoothie with Coconut Water
18132                                    Flying Scotsman
18133                               Maiden's Blush No.ii
18233                                                Elk
18292                                          Sloeberry
18331                  Lime Daiquiri with Apricot Brandy
18359                                            Stanley
18405                             Honeydew-Kiwi Smoothie
18518                           Pan-Fried Hawaiian Pizza
18644                                     Spring Feeling
18772                                          Dry Bronx
19044                               Coriander Lime Pesto
19273                                       Rhett Butler
19695                                           Nineteen
19922                                           Mexicano
19939                                             Alaska
20078                                       Self-Starter
20115                                            Russian

                                            instructions  total_time  \
137    Stir together all ingredients in a bowl until ...         NaN
348     Blend all ingredients in a blender until smooth.         NaN
453    Bring ingredients to boil over -high heat, sti...       250.0
527    Combine all ingredients in a mixing glass and ...         NaN
528    Combine all ingredients in a cocktail shaker a...         NaN
547    Combine all ingredients in a cocktail shaker a...         NaN
577    Combine all ingredients except the soda in a c...         NaN
590    Combine all ingredients except the peel and ch...         NaN
758    Rub the rim of a cocktail glass with lime, the...         NaN
770    Combine all ingredients in a mixing glass and ...         NaN
951                                                              NaN
1076                                                             NaN
1453                                                             NaN
1466   Combine all ingredients in a mixing glass and ...         NaN
1484   Stir together all ingredients in a bowl until ...         NaN
1602   Combine all ingredients in a mixing glass and ...         NaN
1659   Combine ingredients in a mixing glass and stir...         NaN
1796   Combine all ingredients in a mixing glass and ...         NaN
1959   Combine all ingredients, except the cherry, in...         NaN
2254   Preheat the broiler. Add a little oil to a  ca...        11.0
2354                      Stir together all ingredients.         NaN
2540                                                             NaN
2596   Combine all the ingredients except the olive i...         NaN
2677   Combine all ingredients in a cocktail shaker a...         NaN
2692   Place the watermelon in a  mixing bowl. Add th...         NaN
2725                                                             NaN
2835   Combine all ingredients in a mixing glass and ...         NaN
2847                                                             NaN
2963   Combine all ingredients in a cocktail shaker a...         NaN
3019   Combine all ingredients in a mixing glass and ...         NaN
3055   Combine all ingredients in a cocktail shaker a...         NaN
3294   In a food processor blend together all ingredi...         NaN
3672   Combine all ingredients in blender and process...         NaN
3746    Blend all ingredients in a blender until smooth.         NaN
3800   Combine all ingredients in a cocktail shaker a...         NaN
3926   Combine all ingredients in a cocktail shaker a...         NaN
3945   Combine all ingredients in a cocktail shaker a...         NaN
3972   Combine all ingredients except the soda in a c...         NaN
4029   Combine all ingredients in a mixing glass and ...         NaN
4156   Combine all ingredients in a cocktail shaker a...         NaN
4424   Combine all ingredients in a cocktail shaker a...         NaN
4450   Divide nectar and bitters between 2 chilled ch...         NaN
4475   Combine all ingredients in a cocktail shaker a...         NaN
4656   Combine all ingredients in a cocktail shaker a...         NaN
4950   Combine all ingredients in a mixing glass and ...         NaN
5017   Combine all ingredients in a cocktail shaker a...         NaN
5030   Combine all ingredients in a cocktail shaker a...         NaN
5102   Combine all ingredients in a cocktail shaker a...         NaN
5126   Combine all ingredients in a cocktail shaker a...         NaN
5673   Combine all ingredients in a cocktail shaker a...         NaN
5849   Place ingredients in blender in the order list...         NaN
5851   Combine all ingredients in a mixing glass and ...         NaN
5942   Combine all ingredients in a cocktail shaker a...         NaN
5982   Combine all ingredients in a mixing glass and ...         NaN
6148   Combine all ingredients in a cocktail shaker a...         NaN
6248                                                             NaN
6305   Combine all ingredients in a cocktail shaker a...         NaN
6578   Combine all ingredients in a cocktail shaker a...         NaN
6706   Combine all ingredients in a cocktail shaker a...         NaN
6816    Blend all ingredients in a blender until smooth.         NaN
6927   Pour all of the ingredients into a highball gl...         NaN
7072   Combine all ingredients in a cocktail shaker a...         NaN
7091   Pour all of the ingredients into a highball gl...         NaN
7200   Combine all ingredients in a mixing glass and ...         NaN
7365                                                             NaN
7425   Combine all ingredients in a cocktail shaker a...         NaN
7467   Combine all ingredients in a mixing glass and ...         NaN
7572   Combine all ingredients in a mixing glass and ...         NaN
8024   Combine all ingredients in a mixing glass and ...         NaN
8042   Rub the rim of a cocktail glass with lime, the...         NaN
8154    Blend all ingredients in a blender until smooth.         NaN
8215   Combine all ingredients, except peel, in a mix...         NaN
8290   Combine all ingredients in a mixing glass and ...         NaN
8345   Mix all ingredients in  bowl. Season to taste ...       360.0
8394   Combine all ingredients in a cocktail shaker a...         NaN
8689   Combine all ingredients in a mixing glass and ...         NaN
8870   Combine all ingredients, except peel, in a mix...         NaN
9040   Combine all ingredients in a cocktail shaker a...         NaN
9215   Combine all ingredients in a cocktail shaker a...         NaN
9291   Combine all ingredients in a cocktail shaker a...         NaN
9593   Divide nectar and bitters between 2 chilled ch...         NaN
9882   Puree berries in processor. Press puree throug...         NaN
9916   Combine all ingredients in a cocktail shaker a...         NaN
10210  Combine all ingredients in a cocktail shaker a...         NaN
10287  Combine all ingredients in a cocktail shaker a...         NaN
10512  Combine all ingredients in a cocktail shaker a...         NaN
10613  Combine all ingredients in a mixing glass and ...         NaN
10649  Place ingredients in blender in the order list...         NaN
10658  Combine ingredients in a mixing glass and stir...         NaN
10761  Combine all ingredients in a mixing glass and ...         NaN
10939  Combine all ingredients in a cocktail shaker a...         NaN
11015  Combine all ingredients in a cocktail shaker a...         NaN
11104  Combine all ingredients in a cocktail shaker a...         NaN
11195  Combine all ingredients except the peel and ch...         NaN
11317  Combine all ingredients in a cocktail shaker a...         NaN
11479                     Stir together all ingredients.         NaN
11508  Combine all ingredients in a cocktail shaker a...         NaN
11673  Combine all ingredients in a mixing glass and ...         NaN
12004  Combine all ingredients in a mixing glass and ...         NaN
12124   Blend all ingredients in a blender until smooth.         NaN
12330  Combine all ingredients in a cocktail shaker a...         NaN
12378  Combine all ingredients in a mixing glass and ...         NaN
12382  Stud the orange with cloves and roast in a 350...        50.0
12388  Combine all ingredients in a cocktail shaker a...         NaN
12454  Combine all ingredients in a mixing glass and ...         NaN
12493  Combine all ingredients in a mixing glass and ...         NaN
12530  Stir together all ingredients in a bowl until ...         NaN
12993  Combine all ingredients except the soda in a c...         NaN
13021  Combine all ingredients in a cocktail shaker a...         NaN
13066  Combine all ingredients in a mixing glass and ...         NaN
13093  Combine all ingredients in a cocktail shaker a...         NaN
13110  Stud the orange with cloves and roast in a 350...        50.0
13135  Combine all ingredients, except the peel, in a...         NaN
13165  Combine all ingredients in a cocktail shaker a...         NaN
13374  Combine all ingredients in a cocktail shaker a...         NaN
13526  Combine all ingredients in a mixing glass and ...         NaN
13627  Combine all ingredients in a cocktail shaker a...         NaN
13851  Combine ingredients in a mixing glass and stir...         NaN
14071  Combine all ingredients in a cocktail shaker a...         NaN
14288  Stir together all ingredients in a bowl until ...         NaN
14355  Combine all ingredients in a cocktail shaker a...         NaN
14376  Combine all ingredients in a mixing glass and ...         NaN
14481  Combine all the ingredients except the olive i...         NaN
14578  Combine all ingredients in a cocktail shaker a...         NaN
14614  Combine all ingredients in a cocktail shaker a...         NaN
14619  Combine all ingredients in a cocktail shaker a...         NaN
14664  Combine all ingredients in a mixing glass and ...         NaN
14763  Mix all ingredients in  bowl. Season to taste ...       360.0
14890  Combine all ingredients, except the peel, in a...         NaN
14965  Combine all ingredients in a mixing glass and ...         NaN
15022  Combine all ingredients in a cocktail shaker a...         NaN
15499  Combine all ingredients in a cocktail shaker a...         NaN
15649  Combine all ingredients in a cocktail shaker a...         NaN
15684  Combine ingredients in a mixing glass and stir...         NaN
15752  Combine all ingredients in a cocktail shaker a...         NaN
15774  Combine all ingredients except the soda in a c...         NaN
15778  Combine all ingredients in a mixing glass and ...         NaN
15835  Combine all ingredients in a cocktail shaker a...         NaN
15907  Puree berries in processor. Press puree throug...         NaN
15914  Bring ingredients to boil over -high heat, sti...       250.0
16014  Combine all ingredients in a mixing glass and ...         NaN
16135  Place ingredients in blender in the order list...         NaN
16405  Combine all ingredients in a cocktail shaker a...         NaN

In [173]:
filtered_df_all

,name,instructions,total_time,ingredient_names
0,"Lentil, Apple, and Turkey Wrap","1. Place the stock, lentils, celery, carrot, t...",30.0,"[low-sodium vegetable or chicken stock, dried ..."
1,Boudin Blanc Terrine with Red Onion Confit,Combine first 9 ingredients in heavy saucepan...,177.0,"[whipping cream, onions, chopped, salt, bay le..."
2,Potato and Fennel Soup Hodge,In a heavy saucepan cook diced fennel and oni...,40.0,"[fennel bulb (sometimes called anise), stalks ..."
3,Mahi-Mahi in Tomato Olive Sauce,Heat oil in heavy skillet over -high heat. Ad...,22.0,"[extra-virgin olive oil, chopped onion, dry wh..."
4,Spinach Noodle Casserole,Preheat oven to 350°F. Lightly grease 8x8x2-in...,55.0,"[12-ounce package frozen spinach soufflé, tha..."
...,...,...,...,...
20124,Chinese Barbecued Spareribs,Wash spareribs. Remove excess fat and gristle....,30.0,"[side pork spareribs, about 3 pounds, soy sauc..."
20126,Artichoke and Parmesan Risotto,Bring broth to simmer in saucepan.Remove from ...,41.0,"[(or more) low-salt chicken broth, butter, div..."
20127,Turkey Cream Puff Pie,"Using a sharp knife, cut a shallow X in bottom...",67.0,"[tomato, onion, finely chopped (1/2 cup), unsa..."
20128,Snapper on Angel Hair with Citrus Cream,Heat 2 tablespoons oil in heavy skillet over ...,14.0,"[olive oil, shallots, thinly sliced (about 1/2..."
20129,Baked Ham with Marmalade-Horseradish Glaze,Position rack in bottom third of oven and preh...,150.0,"[18-pound fully cooked bone-in smoked ham, roo..."

In [ ]:
filtered_df_all.to_parquet('deduplicated_recipes_Epicurious.parquet', index=False)

print("Deduplication complete! Results saved to:")
print(" - deduplicated_recipes_Epicurious.parquet (deduplicated data)")